// code generated by ifacemaker; DO NOT EDIT.

package helpers

// InterfaceEnvironmentHelper is the interface implemented by EnvironmentHelper
type InterfaceEnvironmentHelper interface {
	// Get tries to get the value and fills the error field on fail.
	Get(environmentVariable string) string
	// Error exposes the error or nil.
	Error() error
	// GetString returns an environment value as a string ( if found ).
	GetString(key string) (string, error)
	// GetInteger returns an environment value as an integer ( if found ).
	GetInteger(key string) (int, error)
	// GetBoolean returns an environment value as a boolean ( if found ).
	GetBoolean(key string) (bool, error)
}
