// code generated by ifacemaker; DO NOT EDIT.

package logger

import (
	"context"

	"go.uber.org/zap"
)

// InterfaceLogger is the interface implemented by Logger
type InterfaceLogger interface {
	// GetZapLogger returns the zap implementation used by the logger.
	GetZapLogger() *zap.Logger
	// Log wraps the zap logger with the needed context variables to match it to the apm trace.
	Log(ctx context.Context) InterfaceZapLogger
}
