// Code generated by mockery. DO NOT EDIT.

package presenters

import mock "github.com/stretchr/testify/mock"

// MockInterfacePresenter is an autogenerated mock type for the InterfacePresenter type
type MockInterfacePresenter struct {
	mock.Mock
}

// Error provides a mock function with given fields: statusCode, err
func (_m *MockInterfacePresenter) Error(statusCode int, err error) {
	_m.Called(statusCode, err)
}

// Success provides a mock function with given fields: statusCode, data
func (_m *MockInterfacePresenter) Success(statusCode int, data interface{}) {
	_m.Called(statusCode, data)
}

type mockConstructorTestingTNewMockInterfacePresenter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInterfacePresenter creates a new instance of MockInterfacePresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterfacePresenter(t mockConstructorTestingTNewMockInterfacePresenter) *MockInterfacePresenter {
	mock := &MockInterfacePresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
