// Code generated by mockery. DO NOT EDIT.

package bundb

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"

	schema "github.com/uptrace/bun/schema"

	sql "database/sql"
)

// MockInterfaceDropIndexQuery is an autogenerated mock type for the InterfaceDropIndexQuery type
type MockInterfaceDropIndexQuery struct {
	mock.Mock
}

// AppendQuery provides a mock function with given fields: fmter, b
func (_m *MockInterfaceDropIndexQuery) AppendQuery(fmter schema.Formatter, b []byte) ([]byte, error) {
	ret := _m.Called(fmter, b)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(schema.Formatter, []byte) []byte); ok {
		r0 = rf(fmter, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(schema.Formatter, []byte) error); ok {
		r1 = rf(fmter, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Concurrently provides a mock function with given fields:
func (_m *MockInterfaceDropIndexQuery) Concurrently() InterfaceDropIndexQuery {
	ret := _m.Called()

	var r0 InterfaceDropIndexQuery
	if rf, ok := ret.Get(0).(func() InterfaceDropIndexQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDropIndexQuery)
		}
	}

	return r0
}

// Conn provides a mock function with given fields: db
func (_m *MockInterfaceDropIndexQuery) Conn(db bun.IConn) InterfaceDropIndexQuery {
	ret := _m.Called(db)

	var r0 InterfaceDropIndexQuery
	if rf, ok := ret.Get(0).(func(bun.IConn) InterfaceDropIndexQuery); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDropIndexQuery)
		}
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, dest
func (_m *MockInterfaceDropIndexQuery) Exec(ctx context.Context, dest ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, dest...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(ctx, dest...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IfExists provides a mock function with given fields:
func (_m *MockInterfaceDropIndexQuery) IfExists() InterfaceDropIndexQuery {
	ret := _m.Called()

	var r0 InterfaceDropIndexQuery
	if rf, ok := ret.Get(0).(func() InterfaceDropIndexQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDropIndexQuery)
		}
	}

	return r0
}

// Index provides a mock function with given fields: query, args
func (_m *MockInterfaceDropIndexQuery) Index(query string, args ...interface{}) InterfaceDropIndexQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDropIndexQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceDropIndexQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDropIndexQuery)
		}
	}

	return r0
}

// Model provides a mock function with given fields: model
func (_m *MockInterfaceDropIndexQuery) Model(model interface{}) InterfaceDropIndexQuery {
	ret := _m.Called(model)

	var r0 InterfaceDropIndexQuery
	if rf, ok := ret.Get(0).(func(interface{}) InterfaceDropIndexQuery); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDropIndexQuery)
		}
	}

	return r0
}

// Operation provides a mock function with given fields:
func (_m *MockInterfaceDropIndexQuery) Operation() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Restrict provides a mock function with given fields:
func (_m *MockInterfaceDropIndexQuery) Restrict() InterfaceDropIndexQuery {
	ret := _m.Called()

	var r0 InterfaceDropIndexQuery
	if rf, ok := ret.Get(0).(func() InterfaceDropIndexQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDropIndexQuery)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockInterfaceDropIndexQuery interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInterfaceDropIndexQuery creates a new instance of MockInterfaceDropIndexQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterfaceDropIndexQuery(t mockConstructorTestingTNewMockInterfaceDropIndexQuery) *MockInterfaceDropIndexQuery {
	mock := &MockInterfaceDropIndexQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
