// Code generated by mockery. DO NOT EDIT.

package bundb

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"

	schema "github.com/uptrace/bun/schema"

	sql "database/sql"
)

// MockInterfaceDeleteQuery is an autogenerated mock type for the InterfaceDeleteQuery type
type MockInterfaceDeleteQuery struct {
	mock.Mock
}

// AppendQuery provides a mock function with given fields: fmter, b
func (_m *MockInterfaceDeleteQuery) AppendQuery(fmter schema.Formatter, b []byte) ([]byte, error) {
	ret := _m.Called(fmter, b)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(schema.Formatter, []byte) []byte); ok {
		r0 = rf(fmter, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(schema.Formatter, []byte) error); ok {
		r1 = rf(fmter, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Apply provides a mock function with given fields: fn
func (_m *MockInterfaceDeleteQuery) Apply(fn func(InterfaceDeleteQuery) InterfaceDeleteQuery) InterfaceDeleteQuery {
	ret := _m.Called(fn)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(func(InterfaceDeleteQuery) InterfaceDeleteQuery) InterfaceDeleteQuery); ok {
		r0 = rf(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// Conn provides a mock function with given fields: db
func (_m *MockInterfaceDeleteQuery) Conn(db bun.IConn) InterfaceDeleteQuery {
	ret := _m.Called(db)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(bun.IConn) InterfaceDeleteQuery); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, dest
func (_m *MockInterfaceDeleteQuery) Exec(ctx context.Context, dest ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, dest...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(ctx, dest...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ForceDelete provides a mock function with given fields:
func (_m *MockInterfaceDeleteQuery) ForceDelete() InterfaceDeleteQuery {
	ret := _m.Called()

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func() InterfaceDeleteQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// Model provides a mock function with given fields: model
func (_m *MockInterfaceDeleteQuery) Model(model interface{}) InterfaceDeleteQuery {
	ret := _m.Called(model)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(interface{}) InterfaceDeleteQuery); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// ModelTableExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceDeleteQuery) ModelTableExpr(query string, args ...interface{}) InterfaceDeleteQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceDeleteQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// Operation provides a mock function with given fields:
func (_m *MockInterfaceDeleteQuery) Operation() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Returning provides a mock function with given fields: query, args
func (_m *MockInterfaceDeleteQuery) Returning(query string, args ...interface{}) InterfaceDeleteQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceDeleteQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// Table provides a mock function with given fields: tables
func (_m *MockInterfaceDeleteQuery) Table(tables ...string) InterfaceDeleteQuery {
	_va := make([]interface{}, len(tables))
	for _i := range tables {
		_va[_i] = tables[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceDeleteQuery); ok {
		r0 = rf(tables...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// TableExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceDeleteQuery) TableExpr(query string, args ...interface{}) InterfaceDeleteQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceDeleteQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// Where provides a mock function with given fields: query, args
func (_m *MockInterfaceDeleteQuery) Where(query string, args ...interface{}) InterfaceDeleteQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceDeleteQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// WhereAllWithDeleted provides a mock function with given fields:
func (_m *MockInterfaceDeleteQuery) WhereAllWithDeleted() InterfaceDeleteQuery {
	ret := _m.Called()

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func() InterfaceDeleteQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// WhereDeleted provides a mock function with given fields:
func (_m *MockInterfaceDeleteQuery) WhereDeleted() InterfaceDeleteQuery {
	ret := _m.Called()

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func() InterfaceDeleteQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// WhereGroup provides a mock function with given fields: sep, fn
func (_m *MockInterfaceDeleteQuery) WhereGroup(sep string, fn func(InterfaceDeleteQuery) InterfaceDeleteQuery) InterfaceDeleteQuery {
	ret := _m.Called(sep, fn)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(string, func(InterfaceDeleteQuery) InterfaceDeleteQuery) InterfaceDeleteQuery); ok {
		r0 = rf(sep, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// WhereOr provides a mock function with given fields: query, args
func (_m *MockInterfaceDeleteQuery) WhereOr(query string, args ...interface{}) InterfaceDeleteQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceDeleteQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// WherePK provides a mock function with given fields: cols
func (_m *MockInterfaceDeleteQuery) WherePK(cols ...string) InterfaceDeleteQuery {
	_va := make([]interface{}, len(cols))
	for _i := range cols {
		_va[_i] = cols[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceDeleteQuery); ok {
		r0 = rf(cols...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

// With provides a mock function with given fields: name, query
func (_m *MockInterfaceDeleteQuery) With(name string, query schema.QueryAppender) InterfaceDeleteQuery {
	ret := _m.Called(name, query)

	var r0 InterfaceDeleteQuery
	if rf, ok := ret.Get(0).(func(string, schema.QueryAppender) InterfaceDeleteQuery); ok {
		r0 = rf(name, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceDeleteQuery)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockInterfaceDeleteQuery interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInterfaceDeleteQuery creates a new instance of MockInterfaceDeleteQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterfaceDeleteQuery(t mockConstructorTestingTNewMockInterfaceDeleteQuery) *MockInterfaceDeleteQuery {
	mock := &MockInterfaceDeleteQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
