// Code generated by mockery. DO NOT EDIT.

package bundb

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"

	schema "github.com/uptrace/bun/schema"

	sql "database/sql"
)

// MockInterfaceUpdateQuery is an autogenerated mock type for the InterfaceUpdateQuery type
type MockInterfaceUpdateQuery struct {
	mock.Mock
}

// AppendQuery provides a mock function with given fields: fmter, b
func (_m *MockInterfaceUpdateQuery) AppendQuery(fmter schema.Formatter, b []byte) ([]byte, error) {
	ret := _m.Called(fmter, b)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(schema.Formatter, []byte) []byte); ok {
		r0 = rf(fmter, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(schema.Formatter, []byte) error); ok {
		r1 = rf(fmter, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Apply provides a mock function with given fields: fn
func (_m *MockInterfaceUpdateQuery) Apply(fn func(InterfaceUpdateQuery) InterfaceUpdateQuery) InterfaceUpdateQuery {
	ret := _m.Called(fn)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(func(InterfaceUpdateQuery) InterfaceUpdateQuery) InterfaceUpdateQuery); ok {
		r0 = rf(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Bulk provides a mock function with given fields:
func (_m *MockInterfaceUpdateQuery) Bulk() InterfaceUpdateQuery {
	ret := _m.Called()

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func() InterfaceUpdateQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Column provides a mock function with given fields: columns
func (_m *MockInterfaceUpdateQuery) Column(columns ...string) InterfaceUpdateQuery {
	_va := make([]interface{}, len(columns))
	for _i := range columns {
		_va[_i] = columns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceUpdateQuery); ok {
		r0 = rf(columns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Conn provides a mock function with given fields: db
func (_m *MockInterfaceUpdateQuery) Conn(db bun.IConn) InterfaceUpdateQuery {
	ret := _m.Called(db)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(bun.IConn) InterfaceUpdateQuery); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// ExcludeColumn provides a mock function with given fields: columns
func (_m *MockInterfaceUpdateQuery) ExcludeColumn(columns ...string) InterfaceUpdateQuery {
	_va := make([]interface{}, len(columns))
	for _i := range columns {
		_va[_i] = columns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceUpdateQuery); ok {
		r0 = rf(columns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, dest
func (_m *MockInterfaceUpdateQuery) Exec(ctx context.Context, dest ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, dest...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(ctx, dest...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FQN provides a mock function with given fields: name
func (_m *MockInterfaceUpdateQuery) FQN(name string) schema.Ident {
	ret := _m.Called(name)

	var r0 schema.Ident
	if rf, ok := ret.Get(0).(func(string) schema.Ident); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(schema.Ident)
	}

	return r0
}

// Model provides a mock function with given fields: model
func (_m *MockInterfaceUpdateQuery) Model(model interface{}) InterfaceUpdateQuery {
	ret := _m.Called(model)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// ModelTableExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceUpdateQuery) ModelTableExpr(query string, args ...interface{}) InterfaceUpdateQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// OmitZero provides a mock function with given fields:
func (_m *MockInterfaceUpdateQuery) OmitZero() InterfaceUpdateQuery {
	ret := _m.Called()

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func() InterfaceUpdateQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Operation provides a mock function with given fields:
func (_m *MockInterfaceUpdateQuery) Operation() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Returning provides a mock function with given fields: query, args
func (_m *MockInterfaceUpdateQuery) Returning(query string, args ...interface{}) InterfaceUpdateQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Set provides a mock function with given fields: query, args
func (_m *MockInterfaceUpdateQuery) Set(query string, args ...interface{}) InterfaceUpdateQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Table provides a mock function with given fields: tables
func (_m *MockInterfaceUpdateQuery) Table(tables ...string) InterfaceUpdateQuery {
	_va := make([]interface{}, len(tables))
	for _i := range tables {
		_va[_i] = tables[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceUpdateQuery); ok {
		r0 = rf(tables...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// TableExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceUpdateQuery) TableExpr(query string, args ...interface{}) InterfaceUpdateQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Value provides a mock function with given fields: column, expr, args
func (_m *MockInterfaceUpdateQuery) Value(column string, expr string, args ...interface{}) InterfaceUpdateQuery {
	var _ca []interface{}
	_ca = append(_ca, column, expr)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, string, ...interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(column, expr, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// Where provides a mock function with given fields: query, args
func (_m *MockInterfaceUpdateQuery) Where(query string, args ...interface{}) InterfaceUpdateQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// WhereAllWithDeleted provides a mock function with given fields:
func (_m *MockInterfaceUpdateQuery) WhereAllWithDeleted() InterfaceUpdateQuery {
	ret := _m.Called()

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func() InterfaceUpdateQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// WhereDeleted provides a mock function with given fields:
func (_m *MockInterfaceUpdateQuery) WhereDeleted() InterfaceUpdateQuery {
	ret := _m.Called()

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func() InterfaceUpdateQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// WhereGroup provides a mock function with given fields: sep, fn
func (_m *MockInterfaceUpdateQuery) WhereGroup(sep string, fn func(InterfaceUpdateQuery) InterfaceUpdateQuery) InterfaceUpdateQuery {
	ret := _m.Called(sep, fn)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, func(InterfaceUpdateQuery) InterfaceUpdateQuery) InterfaceUpdateQuery); ok {
		r0 = rf(sep, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// WhereOr provides a mock function with given fields: query, args
func (_m *MockInterfaceUpdateQuery) WhereOr(query string, args ...interface{}) InterfaceUpdateQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceUpdateQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// WherePK provides a mock function with given fields: cols
func (_m *MockInterfaceUpdateQuery) WherePK(cols ...string) InterfaceUpdateQuery {
	_va := make([]interface{}, len(cols))
	for _i := range cols {
		_va[_i] = cols[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceUpdateQuery); ok {
		r0 = rf(cols...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

// With provides a mock function with given fields: name, query
func (_m *MockInterfaceUpdateQuery) With(name string, query schema.QueryAppender) InterfaceUpdateQuery {
	ret := _m.Called(name, query)

	var r0 InterfaceUpdateQuery
	if rf, ok := ret.Get(0).(func(string, schema.QueryAppender) InterfaceUpdateQuery); ok {
		r0 = rf(name, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceUpdateQuery)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockInterfaceUpdateQuery interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInterfaceUpdateQuery creates a new instance of MockInterfaceUpdateQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterfaceUpdateQuery(t mockConstructorTestingTNewMockInterfaceUpdateQuery) *MockInterfaceUpdateQuery {
	mock := &MockInterfaceUpdateQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
