// Code generated by mockery. DO NOT EDIT.

package bundb

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"

	schema "github.com/uptrace/bun/schema"

	sql "database/sql"
)

// MockInterfaceTruncateTableQuery is an autogenerated mock type for the InterfaceTruncateTableQuery type
type MockInterfaceTruncateTableQuery struct {
	mock.Mock
}

// AppendQuery provides a mock function with given fields: fmter, b
func (_m *MockInterfaceTruncateTableQuery) AppendQuery(fmter schema.Formatter, b []byte) ([]byte, error) {
	ret := _m.Called(fmter, b)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(schema.Formatter, []byte) []byte); ok {
		r0 = rf(fmter, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(schema.Formatter, []byte) error); ok {
		r1 = rf(fmter, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Conn provides a mock function with given fields: db
func (_m *MockInterfaceTruncateTableQuery) Conn(db bun.IConn) InterfaceTruncateTableQuery {
	ret := _m.Called(db)

	var r0 InterfaceTruncateTableQuery
	if rf, ok := ret.Get(0).(func(bun.IConn) InterfaceTruncateTableQuery); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceTruncateTableQuery)
		}
	}

	return r0
}

// ContinueIdentity provides a mock function with given fields:
func (_m *MockInterfaceTruncateTableQuery) ContinueIdentity() InterfaceTruncateTableQuery {
	ret := _m.Called()

	var r0 InterfaceTruncateTableQuery
	if rf, ok := ret.Get(0).(func() InterfaceTruncateTableQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceTruncateTableQuery)
		}
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, dest
func (_m *MockInterfaceTruncateTableQuery) Exec(ctx context.Context, dest ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, dest...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(ctx, dest...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Model provides a mock function with given fields: model
func (_m *MockInterfaceTruncateTableQuery) Model(model interface{}) InterfaceTruncateTableQuery {
	ret := _m.Called(model)

	var r0 InterfaceTruncateTableQuery
	if rf, ok := ret.Get(0).(func(interface{}) InterfaceTruncateTableQuery); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceTruncateTableQuery)
		}
	}

	return r0
}

// Operation provides a mock function with given fields:
func (_m *MockInterfaceTruncateTableQuery) Operation() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Restrict provides a mock function with given fields:
func (_m *MockInterfaceTruncateTableQuery) Restrict() InterfaceTruncateTableQuery {
	ret := _m.Called()

	var r0 InterfaceTruncateTableQuery
	if rf, ok := ret.Get(0).(func() InterfaceTruncateTableQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceTruncateTableQuery)
		}
	}

	return r0
}

// Table provides a mock function with given fields: tables
func (_m *MockInterfaceTruncateTableQuery) Table(tables ...string) InterfaceTruncateTableQuery {
	_va := make([]interface{}, len(tables))
	for _i := range tables {
		_va[_i] = tables[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceTruncateTableQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceTruncateTableQuery); ok {
		r0 = rf(tables...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceTruncateTableQuery)
		}
	}

	return r0
}

// TableExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceTruncateTableQuery) TableExpr(query string, args ...interface{}) InterfaceTruncateTableQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceTruncateTableQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceTruncateTableQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceTruncateTableQuery)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockInterfaceTruncateTableQuery interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInterfaceTruncateTableQuery creates a new instance of MockInterfaceTruncateTableQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterfaceTruncateTableQuery(t mockConstructorTestingTNewMockInterfaceTruncateTableQuery) *MockInterfaceTruncateTableQuery {
	mock := &MockInterfaceTruncateTableQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
