// Code generated by mockery. DO NOT EDIT.

package bundb

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"

	schema "github.com/uptrace/bun/schema"

	sql "database/sql"
)

// MockInterfaceInsertQuery is an autogenerated mock type for the InterfaceInsertQuery type
type MockInterfaceInsertQuery struct {
	mock.Mock
}

// AppendQuery provides a mock function with given fields: fmter, b
func (_m *MockInterfaceInsertQuery) AppendQuery(fmter schema.Formatter, b []byte) ([]byte, error) {
	ret := _m.Called(fmter, b)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(schema.Formatter, []byte) []byte); ok {
		r0 = rf(fmter, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(schema.Formatter, []byte) error); ok {
		r1 = rf(fmter, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Apply provides a mock function with given fields: fn
func (_m *MockInterfaceInsertQuery) Apply(fn func(InterfaceInsertQuery) InterfaceInsertQuery) InterfaceInsertQuery {
	ret := _m.Called(fn)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(func(InterfaceInsertQuery) InterfaceInsertQuery) InterfaceInsertQuery); ok {
		r0 = rf(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Column provides a mock function with given fields: columns
func (_m *MockInterfaceInsertQuery) Column(columns ...string) InterfaceInsertQuery {
	_va := make([]interface{}, len(columns))
	for _i := range columns {
		_va[_i] = columns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceInsertQuery); ok {
		r0 = rf(columns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// ColumnExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceInsertQuery) ColumnExpr(query string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Conn provides a mock function with given fields: db
func (_m *MockInterfaceInsertQuery) Conn(db bun.IConn) InterfaceInsertQuery {
	ret := _m.Called(db)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(bun.IConn) InterfaceInsertQuery); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// ExcludeColumn provides a mock function with given fields: columns
func (_m *MockInterfaceInsertQuery) ExcludeColumn(columns ...string) InterfaceInsertQuery {
	_va := make([]interface{}, len(columns))
	for _i := range columns {
		_va[_i] = columns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceInsertQuery); ok {
		r0 = rf(columns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, dest
func (_m *MockInterfaceInsertQuery) Exec(ctx context.Context, dest ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, dest...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(ctx, dest...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ignore provides a mock function with given fields:
func (_m *MockInterfaceInsertQuery) Ignore() InterfaceInsertQuery {
	ret := _m.Called()

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func() InterfaceInsertQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Model provides a mock function with given fields: model
func (_m *MockInterfaceInsertQuery) Model(model interface{}) InterfaceInsertQuery {
	ret := _m.Called(model)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(interface{}) InterfaceInsertQuery); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// ModelTableExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceInsertQuery) ModelTableExpr(query string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// OnConflict provides a mock function with given fields: s, args
func (_m *MockInterfaceInsertQuery) OnConflict(s string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(s, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Operation provides a mock function with given fields:
func (_m *MockInterfaceInsertQuery) Operation() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Replace provides a mock function with given fields:
func (_m *MockInterfaceInsertQuery) Replace() InterfaceInsertQuery {
	ret := _m.Called()

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func() InterfaceInsertQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Returning provides a mock function with given fields: query, args
func (_m *MockInterfaceInsertQuery) Returning(query string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Set provides a mock function with given fields: query, args
func (_m *MockInterfaceInsertQuery) Set(query string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Table provides a mock function with given fields: tables
func (_m *MockInterfaceInsertQuery) Table(tables ...string) InterfaceInsertQuery {
	_va := make([]interface{}, len(tables))
	for _i := range tables {
		_va[_i] = tables[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(...string) InterfaceInsertQuery); ok {
		r0 = rf(tables...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// TableExpr provides a mock function with given fields: query, args
func (_m *MockInterfaceInsertQuery) TableExpr(query string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Value provides a mock function with given fields: column, expr, args
func (_m *MockInterfaceInsertQuery) Value(column string, expr string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, column, expr)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(column, expr, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// Where provides a mock function with given fields: query, args
func (_m *MockInterfaceInsertQuery) Where(query string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// WhereOr provides a mock function with given fields: query, args
func (_m *MockInterfaceInsertQuery) WhereOr(query string, args ...interface{}) InterfaceInsertQuery {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, ...interface{}) InterfaceInsertQuery); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

// With provides a mock function with given fields: name, query
func (_m *MockInterfaceInsertQuery) With(name string, query schema.QueryAppender) InterfaceInsertQuery {
	ret := _m.Called(name, query)

	var r0 InterfaceInsertQuery
	if rf, ok := ret.Get(0).(func(string, schema.QueryAppender) InterfaceInsertQuery); ok {
		r0 = rf(name, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceInsertQuery)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockInterfaceInsertQuery interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInterfaceInsertQuery creates a new instance of MockInterfaceInsertQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterfaceInsertQuery(t mockConstructorTestingTNewMockInterfaceInsertQuery) *MockInterfaceInsertQuery {
	mock := &MockInterfaceInsertQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
