// code generated by ifacemaker; DO NOT EDIT.

package helpers

import (
	"context"
	"io"
)

// InterfaceRequestHelper is the interface implemented by RequestHelper
type InterfaceRequestHelper interface {
	// Request handles a request to an external service / api.
	Request(ctx context.Context, method, url string, body io.Reader, headers map[string]string) ([]byte, error)
}
