// Code generated by mockery. DO NOT EDIT.

package convert

import mock "github.com/stretchr/testify/mock"

// MockNumber is an autogenerated mock type for the Number type
type MockNumber struct {
	mock.Mock
}

type mockConstructorTestingTNewMockNumber interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockNumber creates a new instance of MockNumber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockNumber(t mockConstructorTestingTNewMockNumber) *MockNumber {
	mock := &MockNumber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
