// Code generated by mockery. DO NOT EDIT.

package convert

import mock "github.com/stretchr/testify/mock"

// MockFloat is an autogenerated mock type for the Float type
type MockFloat struct {
	mock.Mock
}

type mockConstructorTestingTNewMockFloat interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFloat creates a new instance of MockFloat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFloat(t mockConstructorTestingTNewMockFloat) *MockFloat {
	mock := &MockFloat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
