// code generated by ifacemaker; DO NOT EDIT.

package helpers

import (
	"time"
)

// InterfaceTimeHelper is the interface implemented by TimeHelper
type InterfaceTimeHelper interface {
	// Now returns the current time.
	Now() time.Time
	// NowIn returns the current time at the given location string.
	NowIn(locationName, fallbackLocationName string) time.Time
	// NewDate is a shortcut that returns a new UTC date.
	NewDate(year int, month time.Month, day int) time.Time
}
